#!/bin/bash

TARGET=app.py

export ROOT=tmp
export TOKEN="wowziesdebugboobsyey"

provision() {
  git init $ROOT
}

build() {
	lift build
}

deploy() {
  lift deploy
}

serve() {
  python $TARGET
}

clean() {
  rm -rf $ROOT
}