#!/bin/bash

CTX=nov
TARGET=app.py
TAG=ghcr.io/dupunkto/scry

export ROOT=tmp
export TOKEN="wowziesdebugboobsyey"

provision() {
  git init $ROOT
}

build() {
	lift build
}

deploy() {
  lift deploy
}

serve() {
  python $TARGET
}

clean() {
  rm -rf $ROOT
}